application:
  port: 8000
  host: 0.0.0.0
  hmac_secret: "super-long-and-secret-random-key-needed-to-verify-message-integrity"
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
  require_ssl: false
email_client:
  base_url: "localhost"
  sender_email: "kinhotelzarate@kinhotelzarate.com"
  authorization_token: "999ffa74-f7c1-46aa-8446-0fe19a4d3022"
  timeout_milliseconds: 10000
redis_uri: "redis://127.0.0.1:6379"
